### ISSUE TITLE
파일 정보 가져오기 : 기반 기술 조사

### ISSUE THREAD

**Issue by kwhyo** [choijungp/Project2#1]
파일정보 관련 기반 기술 조사해주세요.

**Comment by kwhyo** [comment]
stat() : 파일의 정보를 받아오는 함수를 사용하겠습니다. 
#include <sys/stat.h> 
헤더를 사용합니다.

**Comment by choijungp** [comment]
네. 알겠습니다~

**Comment by ldayeon** [comment]
확인했습니다~
