### ISSUE TITLE
파일 수정 날짜 비교 함수 : 코드 테스팅

### ISSUE THREAD

**Issue by kwhyo** [choijungp/Project2#24]
파일 수정 날짜의 비교 함수인 datecmp함수 코드의 테스팅을 진행합니다.
각자 로컬에서 실행테스트 해보시고 문제 없으신지 말해주세요!
혹시 더 나은 코드가 있다면 제시해주셔도 좋습니다.

**Comment by choijungp** [comment]
네 ~ 확인했습니다 :>
문제 없습니다 ~ 수고하셨습니다 !
