### ISSUE TITLE
함수 3,4 번 코드 수정

### ISSUE THREAD

**Issue by choijungp** [choijungp/Project2#25]
지금까지 merge된 코드를 동작시켜본 결과 약간의 문제점을 발견했습니다.
시간 정보를 가져와 저장할 sturct tm type문제인 것 같습니다.
시간에 관련된 함수를 맡은 사람들은 해당 함수를 차례로 수정해서 올려주시길 바랍니다.

**Comment by choijungp** [comment]
제가 먼저 3, 4번 함수를 수정하겠습니다.

**Comment by ldayeon** [comment]
확인했습니다~

**Comment by kwhyo** [comment]
머지되면 제가 datecmp 수정하겠습니다!

**Comment by choijungp** [comment]
merge 했습니다. 효희님 datecmp 함수에 관련된 이슈 작성해주세요.
이 이슈는 close 하겠습니다.
