### ISSUE TITLE
localtime함수 조사

### ISSUE THREAD

**Issue by choijungp** [choijungp/Project2#3]
#include <time.h>   
struct tm* localtime(const time_t *timer);    

time_t 값을 이용해 지역 시간을 기준으로 tm 구조체를 초기화한다.   
timer가 가리키는 time_t형 변수 값을 이용하여 tm 구조체의 멤버들을 초기화 한 뒤 이를 가리키는 포인터를 리턴한다.

**Comment by kwhyo** [comment]
혹시 stat함수 사용하셨나요?

**Comment by choijungp** [comment]
stat 구조체 사용했습니다.

**Comment by ldayeon** [comment]
알겠습니다. 조사 깔끔하네요~
