### ISSUE TITLE
파일 블락수 비교 코드 테스팅

### ISSUE THREAD

**Issue by ldayeon** [choijungp/Project2#7]
테스트하겠습니다.

**Comment by ldayeon** [comment]
테스트 완료했습니다. 오류 없이 잘 돌아가네요~  pull request 하겠습니다.

**Comment by choijungp** [comment]
네 ~ 저도 test하고 오류 없으면 merge하겠습니다.

**Comment by kwhyo** [comment]
넵 이슈도 close해도 될거같아요~
