### ISSUE TITLE
struct tm 구조체 설명

### ISSUE THREAD

**Issue by choijungp** [choijungp/Project2#8]
#include <time.h>

struct tm {
       int tm_sec;     //현재 시각의 초 정보
       int tm_min;    //현재 시각의 분 정보
       int tm_hour;   //현재 시각의 시 정보
       int tm_mday;  //현재 시각의 일 정보
       int tm_mon;   //현재 시각의 월 정보
       int tm_year;    //현재 시각의 년 정보
       int tm_wday;  //현재 시각의 요일 정보
       int tm_yday;   //1월 1일부터 몇 일이 지났나
       int tm_isdst;    //서머 타임제 실시 여부 정보
}

**Comment by ldayeon** [comment]
조사 잘해오셨네요. 좋아요.
